### ISSUE TITLE
"Current Robot" widget can select robot that does not exists on field

### ISSUE THREAD

**Issue by kkimurak** [RoboCup-SSL/grSim#116]
**Describe the bug**
Size of ID selection combo box in "Current Robot" widget is defined when `RobotWidget` object is created, and not updated even robot count is updated.  
So, we can select a robot does not exists on field and it causes segmentation fault.

**To Reproduce**
1. Launch grSim
2. reduce robots count to some value (less than 8 - this is number that is used to initialize robotwidget)
3. set current robots id to higher than robot count
4. Segmentation fault

**Expected behavior**
Size of Robot id selector shrinks to fit to robot count.
e.g. if robots count is 10, maximum id that shown in selector comboBox should be 9

**Screenshots**
Current behavior
![grsim_crash_selector](https://user-images.githubusercontent.com/33391846/81496861-bfc19880-92f5-11ea-9edd-006dc4d2732e.gif)

What I want to see
![grsim_crash_selector_fixed](https://user-images.githubusercontent.com/33391846/81496862-c223f280-92f5-11ea-82a3-7b3ef9927764.gif)

**Desktop (please complete the following information):**
 - OS: Fedora 31, 32, Ubuntu 18.04, 20.04

**Additional context**
Same as #115 . I have solution for this. If accepted (maintainer allows), I can submit pull request soon.

**Comment by mahi97** [comment]
Good Catch! 
Yes, of course, we would be more than happy for a PR
