### ISSUE TITLE
grSim doesn’t simulate two cameras

### ISSUE THREAD

**Issue by Hawk777** [RoboCup-SSL/grSim#12]
The real field uses two cameras. For realism, grSim should simulate two cameras, allowing testing of:
- duplicate detections in the overlap area
- frames lacking some robots/balls (because they are on the other field half)
- registration error causing the two detections of the same object to be in different places

**Comment by mahi97** [comment]
simulation of two, four and even eight camera is done.
The problem that is remain is #39. So I close this issue because #39 exists and simulation two camera it's not an issue anymore.
