### ISSUE TITLE
Wall time vs simulation time

### ISSUE THREAD

**Issue by bucefalog** [RoboCup-SSL/grSim#124]
Hi, would it be possible to report the simulation time on SSL detection packages instead of the wall time?
Current issue is that by reporting wall time instead of simulation time, speed measurements are dependent on cpu load.
If the frame rate increases, by reporting wall time, it looks as if the robot was moving faster and vice versa.

The following (approximate) lines fix the issue:
sslworld.h      line 62:   add 'dReal sim_time = 0;'
sslworld.cpp  line 429: add 'sim_time += last_dt;'
sslworld.cpp  line 712: modify to 'packet->mutable_detection()->set_t_capture(sim_time);'
sslworld.cpp  line 713: modify to 'packet->mutable_detection()->set_t_sent(sim_time);'

Eitherway, thanks for the great software!

**Comment by g3force** [comment]
This sounds quite reasonable. It would also be required for #132.

I actually don't know why a dedicated real time timer is used here. When using real time, why not send a unix timestamp just like ssl-vision does. Anyway, the simulation time is probably much more reasonable.

As there were no complains yet, I would consider this ready to be implemented. @bucefalog would you mind creating a PR with your suggested patch?

**Comment by bucefalog** [comment]
OK, forked the project and created branch sim_time with the suggested patch:
https://github.com/bucefalog/grSim/tree/sim_time

**Comment by g3force** [comment]
Thx, could you also create a pull request from this branch, please? :)

I had a quick look on the patch. Could you remove the unrelated formatting changes?

**Comment by bucefalog** [comment]
Apologies for that! 
Formatting changes removed and pull request created!
