### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by Crafter76** [RoboCup-SSL/grSim#42]
There are a lot of problems which came from the source building. May be the easist way is to build docker container to the project, isn't it?

**Comment by mahi97** [comment]
Great Idea 👍 
But currently I'm so busy for IranOpen competition.
Can you start docker for grSim ?

**Comment by mahi97** [comment]
@bermeom I test it, it will work but for display GUI, I have some problem in macOS so I used x11vnc instead of your way and it solved the problem. 
Did you successfully run it on macOS?

**Comment by g3force** [comment]
Just seeing this issue. Docker image is now available on Docker Hub: https://hub.docker.com/r/robocupssl/grsim

See also https://github.com/RoboCup-SSL/grSim/pull/146
