### ISSUE TITLE
Fix compatibility for both divisions

### ISSUE THREAD

**Issue by jgkamat** [RoboCup-SSL/grSim#66]
This is a follow-up to https://github.com/RoboCup-SSL/grSim/pull/59. 

We are trying to update our software to work with the new field sizes and goal area format (which correspond with grSim, since ssl-vision still hasn't updated), and I noticed that the last checkbox of https://github.com/RoboCup-SSL/grSim/pull/59 was not completed. Is there an easy way to switch between divisions right now, I couldn't find any.

Right, now, the field seems to be incorrect for both divisions [going off of this diagram for quad](https://github.com/RoboCup-SSL/ssl-rules/blob/master/img/quad-size-field.png) [and this diagram for double](https://github.com/RoboCup-SSL/ssl-rules/blob/master/img/double-size-field.png). The goal zone seems to match the quad size goal zone (2.4 by 1.2), but the actual field size seems to match the double field size (6 by 9). 

If possible, could we have a switch to easily switch between the leagues? I would be happy to help with updating the config and adding the switch if you would like, but I wanted to get some feedback/guidance first.

**Comment by mahi97** [comment]
> Right, now, the field seems to be incorrect for both divisions going off of this diagram for quad and this diagram for double. The goal zone seems to match the quad size goal zone (2.4 by 1.2), but the actual field size seems to match the double field size (6 by 9).

The field configs are in vartypes so you can change them and see the result at the same time.
I wanted to make the default values of parameters for division A but as you said it should be fixed for field-size.

> If possible, could we have a switch to easily switch between the leagues? I would be happy to help with updating the config and adding the switch if you would like, but I wanted to get some feedback/guidance first.

I think the easiest way is to add another field config and have both field parameters in the same file, then we can switch the parameters by a hotkey or button in GUI or by a checkbox in vartypes.
