### ISSUE TITLE
Speed up osx travis build by caching

### ISSUE THREAD

**Issue by mahi97** [RoboCup-SSL/grSim#83]
Right now it takes about 30~50 min for building in OSX because of brew package installation.
it can be cached due to reducing this time.

here's a related post:
https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci

**Comment by jpfeltracco** [comment]
I think we can maybe close this? It seems like travis has found a way to speed up their macos builds as they only take ~9 minutes now as shown here: https://travis-ci.org/RoboCup-SSL/grSim/builds/579448208?utm_source=github_status&utm_medium=notification

**Comment by mahi97** [comment]
Thanks for mentioning👍, 9 min is still much longer than Linux builds, but it looks good enough to me.
