### ISSUE TITLE
reset all

### ISSUE THREAD

**Issue by amirbayat98** [RoboCup-SSL/grSim#87]
**Is your feature request related to a problem? Please describe.**
when there is more than 1 robot fell down. its hard to click on everyone of them and click reset. 

**Describe the solution you'd like**
you can add a reset all button.

**Describe alternatives you've considered**

**Additional context**

**Comment by kkimurak** [comment]
Hi, I've implemented such feature. How about this?

![resetAll feature in operation](https://user-images.githubusercontent.com/33391846/82724504-98b19080-9d11-11ea-9463-c0ffef579f3f.gif)

**Comment by mahi97** [comment]
It can be closed thanks to #115 #119
