### ISSUE TITLE
Some links in documents are old

### ISSUE THREAD

**Issue by kkimurak** [RoboCup-SSL/grSim#94]
**overview**
Some links in documentations seems to be old.

**detail**
Here is the know list : 
- [README.md (branch : master)](https://github.com/RoboCup-SSL/grSim/blob/master/README.md)
  - Section "Software Requirements"
    - VarTypes repository
      current : ```[VarTypes Library](https://github.com/szi/vartypes)```  
      It must be : ```[VarTypes Library](https://github.com/jpfeltracco/vartypes) forked from [Szi's Vartypes](https://github.com/szi/vartypes)```
    - Qt
      current : ```[Qt4 Development Libraries](https://www.qt.io) version 4.8+```
      It must be : ```[Qt5 Development Libraries](https://www.qt.io)```
- [INSTALL.md (branch : master, develop)](https://github.com/RoboCup-SSL/grSim/blob/develop/INSTALL.md)
  - Section "Linux/Unix Installation"
    - grSim repository
      current : ```$ git clone https://github.com/mani-monaj/grSim.git```
      It must be : ```$ git clone https://github.com/robocup-ssl/grSim.git```

P.S. I've wrote this believing INSTALL.md is correct (because it has recently updated)

**Comment by mahi97** [comment]
Good points, feel free to send a pull request for this updates, I would really appriciate 😁👍

**Comment by kkimurak** [comment]
(I'm sorry, it seems I added the label by mistake. This is not so serious... )
Thanks, I'll send a pull request soon.

**Comment by mahi97** [comment]
No problem, thanks for your efforts 🖐
